<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1539353739887' stop='1539353754403'>
    <name>Anonymous checkout with coupon:</name>
    <title>Anonymous checkout with coupon:</title>
    <test-cases>
        <test-case start='1539353739888' status='failed' stop='1539353753731'>
            <name>[Positive] as anonymous user I be able to do checkout with coupon</name>
            <title>[Positive] as anonymous user I be able to do checkout with coupon</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1539353744720' status='passed' stop='1539353751162'>
                    <name>I am on page "/"</name>
                    <title>I am on page "/"</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1539353751162' status='passed' stop='1539353753700'>
                    <name>I click "//a[text()='Cell phones']"</name>
                    <title>I click "//a[text()='Cell phones']"</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1539353753700' status='passed' stop='1539353753728'>
                    <name>I wait in url "/cell-phones"</name>
                    <title>I wait in url "/cell-phones"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments>
                <attachment title='Last Seen Screenshot' source='ef4bfc12-7965-4a9c-852f-fae9d43ddf94-attachment.png' type='image/png' size='295968'/>
            </attachments>
            <failure>
                <message>productListPage.productList.productListItem.addToCardButton.count is not a function</message>
                <stack-trace>TypeError: productListPage.productList.productListItem.addToCardButton.count is not a function
                    at Test.Scenario (/home/aleksandr/QualityGate/tests/e2eAnonymousCheckoutWithCoupon_test.js:10:71)
                    at Context.test.fn (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/lib/scenario.js:98:26)
                    at callFnAsync (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:377:21)
                    at Test.Runnable.run (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:324:7)
                    at Runner.runTest (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:442:10)
                    at /home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:560:12
                    at next (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:356:14)
                    at /home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:366:7
                    at next (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:290:14)
                    at /home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:329:7</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>