<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1539354481076' stop='1539354495917'>
    <name>Anonymous checkout with coupon:</name>
    <title>Anonymous checkout with coupon:</title>
    <test-cases>
        <test-case start='1539354481083' status='failed' stop='1539354495194'>
            <name>[Positive] as anonymous user I be able to do checkout with coupon</name>
            <title>[Positive] as anonymous user I be able to do checkout with coupon</title>
            <labels/>
            <parameters/>
            <steps>
                <step start='1539354484972' status='passed' stop='1539354491473'>
                    <name>I am on page "/"</name>
                    <title>I am on page "/"</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1539354491473' status='passed' stop='1539354495163'>
                    <name>I click "//a[text()='Cell phones']"</name>
                    <title>I click "//a[text()='Cell phones']"</title>
                    <attachments/>
                    <steps/>
                </step>
                <step start='1539354495163' status='passed' stop='1539354495189'>
                    <name>I wait in url "/cell-phones"</name>
                    <title>I wait in url "/cell-phones"</title>
                    <attachments/>
                    <steps/>
                </step>
            </steps>
            <attachments>
                <attachment title='Last Seen Screenshot' source='12e5e8a1-0b6c-4a59-8216-7756c8dd4edb-attachment.png' type='image/png' size='295968'/>
            </attachments>
            <failure>
                <message>count is not defined</message>
                <stack-trace>ReferenceError: count is not defined
                    at Test.Scenario (/home/aleksandr/QualityGate/tests/e2eAnonymousCheckoutWithCoupon_test.js:10:7)
                    at Context.test.fn (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/lib/scenario.js:98:26)
                    at callFnAsync (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:377:21)
                    at Test.Runnable.run (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runnable.js:324:7)
                    at Runner.runTest (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:442:10)
                    at /home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:560:12
                    at next (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:356:14)
                    at /home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:366:7
                    at next (/home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:290:14)
                    at /home/aleksandr/.nvm/versions/node/v10.9.0/lib/node_modules/codeceptjs/node_modules/mocha/lib/runner.js:329:7</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>